[versions]
agp = "8.3.1"
coreVersion = "12.1.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
firebaseCrashlytics = "19.0.2"
gradle = "8.1.0"
googleServices = "4.4.2"
firebaseCrashlyticsGradle = "3.0.2"
annotationJvm = "1.8.2"
volley = "1.2.1"
core = "1.13.1"

[libraries]
androidyoutubeplayer-core = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "coreVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
core = { group = "androidx.core", name = "core", version.ref = "core" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

